In [1]:
from sklearn.datasets import make_classification
from sklearn.utils import resample
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = make_classification(n_samples=1000, n_classes=2, random_state=23)

In [3]:
df = pd.DataFrame(data[0], columns=[f"feature_{i}"for i in range(len(data[0][0]))])

In [4]:
df["target"] = data[1]

In [6]:
df.shape

(1000, 21)

In [7]:
from sklearn.decomposition import PCA

In [8]:
pca = PCA(n_components=5)

In [12]:
new_df = pca.fit_transform(df.drop("target", axis=1))

In [15]:
new_df

array([[-0.78714066,  1.28963632, -1.22500216,  1.16723728, -2.57882254],
       [-0.89012413, -0.15275873,  1.00915323, -0.56190352,  0.69775701],
       [ 1.83609228, -1.60921692,  1.14152728,  0.82817206, -1.69832722],
       ...,
       [ 1.85476549,  0.23389007,  0.77388376, -0.63175539, -1.21999221],
       [ 2.18002221,  0.20251416, -0.99363344, -0.11948608,  1.46609668],
       [-1.3252153 , -0.36722113,  0.27565043,  1.08996839, -0.55769495]])

In [16]:
X = new_df
y = df["target"]

In [17]:
new = np.random.rand(20)

In [18]:
new

array([0.08660006, 0.63998945, 0.95325084, 0.33698759, 0.93702138,
       0.34417017, 0.37598781, 0.47830394, 0.76967284, 0.04493339,
       0.62594277, 0.77329949, 0.35627729, 0.13387193, 0.26458888,
       0.68251111, 0.86599784, 0.62492817, 0.29984461, 0.37203942])

In [20]:
pca.transform([new])

C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but PCA was fitted with feature names
  warnings.warn(


array([[ 0.06119645,  0.51289151,  0.2460839 , -0.55984146, -0.44494352]])